### ISSUE TITLE
NER datasets

### ISSUE THREAD

**Issue by SUSTechBruce** [Nardien/KALA#1]
Hi, could you supply the well-preprocessed ner dataset, please?

**Comment by Nardien** [comment]
Thank you for your interest in our work! You can get the preprocessed version of the ner dataset following the codes in the `KGC` folder, as we already described in the Knowledge Graph Construction section in README.
However, we also plan to upload the preprocessed version.

**Comment by JinheonBaek** [comment]
Hi,

Thank you for your interest.
In regard to preprocessed NER datasets, you can directly download them with the following link: https://1drv.ms/u/s!Aj5JerV8SMDyi59jrrKrSK-HUw6wGQ?e=paPdRX.
For details, see https://github.com/Nardien/KALA/pull/2 . 

If you have any further questions, feel free to let us know. :)

**Comment by JinheonBaek** [comment]
As I provided the preprocessed ner dataset, I close this issue. If any issues arise, feel free to re-open it.

**Comment by jiangxinke** [comment]
Hi, could you supply the EMRQA dataset? The origin dataset is not available yet. (I have signed the protocol)
